# drop table user;
# drop table city;
# create table city
# (
#     id   bigint auto_increment
#         primary key,
#     name varchar(50) not null
# );
#
# create table user
# (
#     id   bigint auto_increment
#         primary key,
#     name varchar(50) not null,
#     city bigint      null,
#     age  int         not null default 0,
#     constraint fk_users_city_id
#         foreign key (city) references city (id)
# );
#
# INSERT INTO city (name)
# VALUES ('New York'),
#        ('Los Angeles'),
#        ('Chicago'),
#        ('Houston'),
#        ('Phoenix'),
#        ('Philadelphia'),
#        ('San Antonio'),
#        ('San Diego'),
#        ('Dallas'),
#        ('San Jose'),
#        ('Austin'),
#        ('Jacksonville'),
#        ('Fort Worth'),
#        ('Columbus'),
#        ('San Francisco'),
#        ('Charlotte'),
#        ('Indianapolis'),
#        ('Seattle'),
#        ('Denver'),
#        ('Washington'),
#        ('Boston'),
#        ('El Paso'),
#        ('Nashville'),
#        ('Detroit'),
#        ('Oklahoma City'),
#        ('Portland'),
#        ('Las Vegas'),
#        ('Memphis'),
#        ('Louisville'),
#        ('Baltimore'),
#        ('Milwaukee'),
#        ('Albuquerque'),
#        ('Tucson'),
#        ('Fresno'),
#        ('Sacramento'),
#        ('Mesa'),
#        ('Kansas City'),
#        ('Atlanta'),
#        ('Long Beach'),
#        ('Colorado Springs'),
#        ('Raleigh'),
#        ('Miami'),
#        ('Virginia Beach'),
#        ('Omaha'),
#        ('Oakland'),
#        ('Minneapolis'),
#        ('Tulsa'),
#        ('Arlington'),
#        ('New Orleans'),
#        ('Wichita'),
#        ('Cleveland'),
#        ('Tampa'),
#        ('Bakersfield'),
#        ('Aurora'),
#        ('Honolulu'),
#        ('Anaheim'),
#        ('Santa Ana'),
#        ('Corpus Christi'),
#        ('Riverside'),
#        ('St. Louis'),
#        ('Lexington'),
#        ('Stockton'),
#        ('Pittsburgh'),
#        ('Anchorage');
#
# INSERT INTO user (name, city)
# VALUES ('Alice', 1),
#        ('Bob', 2),
#        ('Charlie', 3),
#        ('David', 4),
#        ('Emma', 5),
#        ('Frank', 6),
#        ('Grace', 7),
#        ('Henry', 8),
#        ('Ivy', 9),
#        ('Jack', 10),
#        ('Kate', 11),
#        ('Liam', 12),
#        ('Mia', 13),
#        ('Nathan', 14),
#        ('Olivia', 15),
#        ('Peter', 16),
#        ('Quinn', 17),
#        ('Rachel', 18),
#        ('Samuel', 19),
#        ('Tina', 20),
#        ('Ursula', 21),
#        ('Victor', 22),
#        ('Wendy', 23),
#        ('Xavier', 24),
#        ('Yvonne', 25),
#        ('Zack', 26),
#        ('Ella', 27),
#        ('Noah', 28),
#        ('Sophia', 29),
#        ('Logan', 30),
#        ('Ava', 31),
#        ('James', 32),
#        ('Amelia', 33),
#        ('William', 34),
#        ('Charlotte', 35),
#        ('Michael', 36),
#        ('Isabella', 37),
#        ('Benjamin', 38),
#        ('Abigail', 39),
#        ('Daniel', 40),
#        ('Emily', 41),
#        ('Alexander', 42),
#        ('Elizabeth', 43),
#        ('Christopher', 44),
#        ('Grace', 45),
#        ('Matthew', 46),
#        ('Samantha', 47),
#        ('Lucas', 48),
#        ('Avery', 49),
#        ('Madison', 50);
#
#
